docs/guides/community-inspirations.md
Removed unnecessary `[` and `"` 📝
<a href="https://stackblitz.com/~/github.com/stackblitz/webcontainer-docs/tree/web-publisher/ykmsd/community-inspirations"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Web Publisher](https://developer.stackblitz.com/codeflow/integrating-web-publisher)._
=> fix: remove unnecessary characters in Community Inspirations 

docs/guides/running-processes.md
<a href="https://stackblitz.com/~/github.com/stackblitz/webcontainer-docs/tree/web-publisher/EricSimons/running-processes"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Web Publisher](https://developer.stackblitz.com/codeflow/integrating-web-publisher)._
=> Fix heading typo for "Running Processes" page

docs/guides/introduction.md
This PR fixes a broken url fragment in docs/guides/introduction.md.
=> Fix broken url fragment

docs/tutorial/2-setting-up-webcontainers.md
* /tutorial/2-setting-up-webcontainers uses pnpm, but [Vite starter](https://stackblitz.com/edit/vitejs-vite-jkerkn?file=index.html&terminal=dev) uses npm, so changed it to npm.
* Fix typo (`in in` -> `in`).
=> Use npm for consistency and fix some typos

docs/.vitepress/theme/components/Examples/WCEmbed/utils.ts
This PR adds the ability to bypass the feature and user-agent check in the `isWebContainerSupported` function, by adding any non-empty value for the `webcontainer_any_ua` key in localStorage.
This is intended to allow testing of browsers that we have excluded because they currently do not run WebContainers at all (Safari 16.3 and earlier releases), upcoming versions of those browser (Safari 16.4 Beta and later releases), and other web browsers which happen to run afoul of our simple UA checks for other reasons.
Steps for testing:
1. Use a browser such as Safari.
2. Go to https://webcontainers.io (or, when testing, a Netlify preview deploy for this PR).
3. Open the browser console and run `localStorage.webcontainer_any_ua = 1`.
4. Reload the page.
Expected result:
- We should not show the …
=> feat: allow overriding the user-agent check

docs/.vitepress/theme/styles/fixes.scss
The top nav bar was sized inconsistently on docs and non-docs pages.
|Old|New|
|-|-|
|<img width="1584" alt="Screen Shot 2023-02-21 at 6 17 11 PM" src="https://user-images.githubusercontent.com/22125230/220495716-6ecffa0e-8174-42e7-a884-b1543650b953.png">|<img width="1589" alt="Screen Shot 2023-02-21 at 6 16 44 PM" src="https://user-images.githubusercontent.com/22125230/220495736-143cc48d-0bcb-4f73-a5c5-f871faff4eb4.png">|
=> fix: navbar width inconsistency

docs/.vitepress/theme/styles/content.scss, docs/.vitepress/theme/styles/fixes.scss
DX-34
"Community Tips" blocks needed a facelift, and by proxy, the rest of the `.custom-block` elements also got updated.
- More padding
- Colors brighter / less drab
- Different icons for each block
|Old|New|
|-|-|
|<img width="1687" alt="Screen Shot 2023-02-22 at 11 57 48 PM" src="https://user-images.githubusercontent.com/22125230/220839225-f7c1a2cf-bd16-4734-9176-2721110a2db8.png">|<img width="1685" alt="Screen Shot 2023-02-22 at 11 57 40 PM" src="https://user-images.githubusercontent.com/22125230/220839231-cb8901b1-de52-43a0-89cd-75dae2ea0bfd.png">|
|<img width="1684" alt="Screen Shot 2023-02-22 at 11 58 11 PM" src="https://user-images.githubusercontent.com/22125230/220839266-73c1c212-4e28-438f-b9ec-cb2f45e77227.png">|<img width="1682" alt="Screen Shot 2023-02-22 at 11 58 02 PM" …
=> chore: update/tighten custom-block elements

docs/tutorial/7-add-interactivity.md
I think don't wrap to the next line automatically is not such a good UX practice, right? 🤣
=> docs: typo fix

docs/.vitepress/theme/components/CommunityProjects/CommunityProjects.vue, netlify.toml
So the culprit seemed to be a `v-html` inside a `v-for` which loops over unchanging data imported into the `.vue` component from a `.ts` object.
The bug does NOT exist locally however, only when deployed to Netlify.
Vitepress' docs say that hydration issues like this one can occur from the build process/tool Auto-Minifying the HTML, as Vue uses syntax like `` for placeholders which would obviously be "cleaned up" as benign comments by HTML minification.
https://vitepress.dev/guide/deploy#netlify-vercel-cloudflare-pages-aws-amplify-render
https://github.com/vuejs/vitepress/issues/369#issuecomment-1150970906
However, we don't have HTML minifying enabled on our Netlify build at all, which makes this even more curious:
Regardless, changing the single `<p v-html="project.description" />` to …
=> Fix hydration issue on build

docs/.vitepress/theme/components/Examples/WCEmbed/webcontainer.ts, package-lock.json, package.json
Dogfood our most recent version.
=> chore: upgrade to api 1.1.3

docs/.vitepress/theme/components/Examples/WCEmbed/utils.ts, docs/.vitepress/theme/components/Examples/WCEmbed/webcontainer.ts
This PR will re-enable the terminal on Safari 16.4 and up.
=> chore(safari): enable terminal on Safari 16.4

docs/.vitepress/theme/data/links.ts
This fixes the case studies page to be the new one
-----
<a href="https://stackblitz.com/~/github/stackblitz/webcontainer-docs/tree/samdenty%2Ffix-case-studies"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/stackblitz/webcontainer-docs/tree/samdenty%2Ffix-case-studies)._
=> fix: case studies link

docs/api.md
We were missing the `Uint8Array` type to the `mount` method.
=> fix: add Uint8Array to mount API reference

docs/.vitepress/theme/components/WCUsedByOrgs/WCUsedBy.vue
Fixes DES-118
The `vitepress` `isDark` helper from its `useData()` hook is used in the `WCUsedBy` component, aka "corporate logos" section.
It fires correctly in development, but [not on production](https://github.com/vuejs/vitepress/issues/3267#issuecomment-1855006261), so `isDark` seemed to always default to `false`.
Fixed by wrapping `isDark` calls inside [`<ClientOnly>`](https://vite-plugin-ssr.com/client-only-components) wrappers.
|old|new|
|-|-|
|<img width="1566" alt="Screen Shot 2024-01-20 at 10 04 06 PM" src="https://github.com/stackblitz/webcontainer-docs/assets/22125230/47292175-ed9a-4a5c-a0e6-c6d078e689fe">|<img width="1571" alt="Screen Shot 2024-01-20 at 10 04 36 PM" src="https://github.com/stackblitz/webcontainer-docs/assets/22125230/56912e6d-55ab-47e2-a970-8ff635ab1907">|
=> fix: isDark not firing

docs/.vitepress/theme/components/AuthButtons/AuthButtons.vue, docs/.vitepress/theme/components/AuthButtons/NavBarAuthButtons.vue, docs/.vitepress/theme/components/AuthButtons/NavScreenAuthButtons.vue, docs/.vitepress/theme/components/AuthButtons/linkStyles.scss, docs/.vitepress/theme/components/CustomLayout.vue, docs/.vitepress/theme/styles/fixes.scss
- Same as https://github.com/stackblitz/docs/pull/196, adding Auth Buttons in the nav bar. Any changes made there need to be applied here too. 
- Only difference is I hide the social icons in the nav bar. 
-----
<a href="https://stackblitz.com/~/github/stackblitz/webcontainer-docs/tree/ykmsd%2Fpatch-71213"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github/stackblitz/webcontainer-docs/tree/ykmsd%2Fpatch-71213)._
=> feat: add auth buttons

docs/tutorial/6-connect-a-terminal.md, docs/tutorial/7-add-interactivity.md
As of XTerm 5.4.0, the `xterm` package is deprecated in favor of the `@xterm` org namespace
This PR updates the docs for WebContainers to the new namespace imports
=> docs: migrate to xterm namespaced imports

docs/api.md, docs/guides/quickstart.md, docs/guides/running-processes.md
No related issues.
Hi, thank you for providing Stackblitz and related products.
I, as an OSS maintainer, heavily rely on your products.
Here is a PR to fix some typos and wording in WebContainers documentation.
(Some trailing spaces are removed as well)
⚠️ This is my very first PR for this repository, so I might be missing something important.
=> docs: fix typos

docs/api.md, docs/changelog.md
This PR documents the new `cwd` option which you can pass in when spawning a child process.
=> docs(api): document cwd option for spawning processes

docs/.vitepress/config.ts
- Add back in `API Reference`
- Make `Artificial Intelligence` and ` Commercial Usage` more succinct.
Old:
New:
=> fix: reorganize top links

docs/api.md
This PR documents the new `forwardPreviewErrors` flag.
=> docs(api): add the `forwardPreviewErrors` option

docs/api.md, docs/changelog.md
This PR updates the docs to the latest version `1.3.0`.
=> chore: update docs to v1.3.0

docs/api.md, docs/changelog.md
Documents the new `export()` method.
We have to wait until the latest version of `@webcontainer/api` is released.
=> docs(api): document export method

docs/api.md, docs/changelog.md
This PR updates the docs to version 1.5.0 of `@webcontainer/api`.
=> chore: update docs to 1.5.0
